#!/usr/bin/env node
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import generateModule from "@babel/generator";
import { parse } from "@babel/parser";
import traverseModule from "@babel/traverse";
import { REFERENCE, ROOT, CAPTURES, CLEAN_AGENT } from "./lib/paths.mjs";
import { detectPrimitives } from "./lib/detect.mjs";

const generate = generateModule.default ?? generateModule;
const traverse = traverseModule.default ?? traverseModule;

const newestCapture = () => {
  const files = readdirSync(CAPTURES)
    .filter((file) => file.endsWith(".json"))
    .sort();
  return files.length ? join(CAPTURES, files.at(-1)) : null;
};

const capturePath = process.argv[2] ?? newestCapture();
const source = readFileSync(CLEAN_AGENT, "utf8");
const ast = parse(source, {
  sourceType: "module",
});
const { roles } = detectPrimitives(ast);

function chunking() {
  const builder = roles.requestPath;
  if (!builder) return null;
  let rule = null;
  traverse(ast, {
    FunctionDeclaration(path) {
      if (path.node.id?.name !== builder) return;
      path.traverse({
        CallExpression(callPath) {
          if (rule) return;
          const args = callPath.node.arguments;
          if (args.length !== 3) return;
          if (args[1]?.type !== "NumericLiteral" || args[2]?.type !== "NumericLiteral") return;
          rule = {
            helper: callPath.node.callee.name ?? null,
            seed: generate(args[0], {
              compact: true,
            }).code,
            min: args[1].value,
            max: args[2].value,
          };
        },
      });
    },
  });
  return rule;
}

const templated = (url) =>
  String(url)
    .replace(/\/\d{10,}\.[A-Za-z0-9]+/g, "/<timestamp>.<nonce>")
    .replace(/([?&]q=)[^&]+/, "$1<apiKey>");

function observed() {
  if (!capturePath || !existsSync(capturePath)) return null;
  const capture = JSON.parse(readFileSync(capturePath, "utf8"));
  return (capture.requests ?? []).map((request) => ({
    at: request.t,
    method: request.method,
    url: templated(request.url),
    status: request.status ?? null,
    reqSize: request.reqSize ?? 0,
    encoding: request.decoded?.encoding ?? "-",
    signals: request.signals?.length ?? 0,
  }));
}

const rule = chunking();
const sequence = observed();
const captureName = capturePath ? capturePath.replace(`${ROOT}/`, "") : null;

const out = {
  source: "agent/agent.clean.js",
  capture: sequence ? captureName : null,
  chunking: rule,
  sequence,
};

writeFileSync(join(REFERENCE, "endpoints.json"), JSON.stringify(out, null, 2));

const lines = [
  "# Endpoints",
  "",
  "Generated by `npm run endpoints`. The path rule is read from `agent/agent.clean.js`; the",
  "sequence is whatever a `tools/spy.mjs` capture recorded, so it is one observed run and not a",
  "specification.",
  "",
  "## Path construction",
  "",
];

if (rule) {
  lines.push(
    `\`${roles.requestPath}\` cuts a token into \`/\`-joined chunks. Each chunk length comes from`,
    `\`${rule.helper}(${rule.seed}, ${rule.min}, ${rule.max})\` — a byte of the seed, not a random`,
    `source, so lengths run ${rule.min} to ${rule.max} and the same token always yields the same path.`,
    "",
  );
} else {
  lines.push('Path builder not detected — the `+= "/"` signature no longer matches.', "");
}

lines.push("## Observed sequence", "");

if (sequence?.length) {
  lines.push(
    `From \`${captureName}\`.`,
    "",
    "| t (ms) | method | url | status | req | encoding | signals |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...sequence.map(
      (entry) =>
        `| ${entry.at} | ${entry.method} | \`${entry.url}\` | ${entry.status ?? "-"} | ${entry.reqSize} | ${entry.encoding} | ${entry.signals || "-"} |`,
    ),
    "",
  );
} else {
  lines.push(
    `No capture at \`${captureName}\`. Run \`npm run spy\`, paste the script, save the dump.`,
    "",
  );
}

writeFileSync(join(REFERENCE, "endpoints.md"), `${lines.join("\n")}\n`);

console.log(`chunking ${rule ? `${rule.min}-${rule.max} via ${rule.helper}` : "not detected"}`);

console.log(`sequence ${sequence?.length ?? 0} requests`);
console.log(`out      ${join(REFERENCE, "endpoints.md")}`);
