#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import generateModule from "@babel/generator";
import { parse } from "@babel/parser";
import traverseModule from "@babel/traverse";
import { REFERENCE, CLEAN_AGENT } from "./lib/paths.mjs";
import { detectPrimitives } from "./lib/detect.mjs";

const generate = generateModule.default ?? generateModule;
const traverse = traverseModule.default ?? traverseModule;
const EXPRESSION_WIDTH = 88;
const source = readFileSync(CLEAN_AGENT, "utf8");
const ast = parse(source, {
  sourceType: "module",
});
const { roles } = detectPrimitives(ast);

if (!roles.envelope) {
  console.error("no envelope builder detected — the `s56:` signature no longer matches");
  process.exit(1);
}

const functions = new Map();

traverse(ast, {
  FunctionDeclaration(path) {
    if (path.node.id && path.parentPath.isProgram()) functions.set(path.node.id.name, path);
  },
  VariableDeclarator(path) {
    if (!path.parentPath.parentPath?.isProgram()) return;
    if (path.node.id.type !== "Identifier") return;
    if (path.node.init?.type?.includes("Function"))
      functions.set(path.node.id.name, path.get("init"));
  },
});

const aliases = new Map();

const code = (node) => {
  let text = generate(node, {
    compact: true,
  }).code.replace(/\s+/g, " ");
  for (const [local, name] of aliases)
    text = text.replaceAll(new RegExp(`\\b${local}\\b`, "g"), name);
  return text.length > EXPRESSION_WIDTH ? `${text.slice(0, EXPRESSION_WIDTH - 1)}…` : text;
};

const staticKey = (property) => {
  if (property.computed) return null;
  return property.key?.name ?? property.key?.value ?? null;
};

function envelopeLiteral(path) {
  let found = null;
  path.traverse({
    ObjectExpression(objectPath) {
      if (found) return;
      if (objectPath.node.properties.some((property) => staticKey(property) === "s56")) {
        found = objectPath.node;
      }
    },
  });
  return found;
}

function spreadKeys(name) {
  const helper = functions.get(name);
  if (!helper)
    return {
      keys: [],
      passthrough: false,
    };
  const keys = new Set();
  let passthrough = false;
  helper.traverse({
    ObjectExpression(objectPath) {
      for (const property of objectPath.node.properties) {
        const key = staticKey(property);
        if (key) keys.add(key);
      }
    },
    AssignmentExpression(assignmentPath) {
      const left = assignmentPath.node.left;
      if (left.type !== "MemberExpression") return;
      if (left.computed) {
        passthrough = true;
        return;
      }
      if (left.property.type === "Identifier") keys.add(left.property.name);
    },
  });
  return {
    keys: [...keys].sort(),
    passthrough,
  };
}

const builder = functions.get(roles.envelope);
const literal = envelopeLiteral(builder);

if (!literal) {
  console.error(`${roles.envelope} no longer contains the envelope literal`);
  process.exit(1);
}

for (const param of builder.node.params) {
  if (param.type !== "ObjectPattern") continue;
  for (const property of param.properties) {
    if (property.type === "RestElement") continue;
    const name = staticKey(property);
    const target =
      property.value?.type === "AssignmentPattern" ? property.value.left : property.value;
    if (name && target?.type === "Identifier" && target.name !== name)
      aliases.set(target.name, name);
  }
}

const params = [];

for (const param of builder.node.params) {
  if (param.type !== "ObjectPattern") {
    params.push({
      name: code(param),
      fallback: "",
    });
    continue;
  }
  for (const property of param.properties) {
    if (property.type === "RestElement") {
      params.push({
        name: `...${code(property.argument)}`,
        fallback: "",
      });
      continue;
    }
    const value = property.value;
    params.push({
      name: staticKey(property) ?? code(property.key),
      fallback: value?.type === "AssignmentPattern" ? code(value.right) : "",
    });
  }
}

const rows = [];
const spreads = [];

for (const property of literal.properties) {
  if (property.type === "SpreadElement") {
    const callee = property.argument.callee?.name ?? code(property.argument);
    spreads.push({
      expression: code(property.argument),
      callee,
      ...spreadKeys(callee),
    });
    continue;
  }
  const key = staticKey(property);
  if (!key) continue;
  rows.push({
    key,
    expression: code(property.value),
  });
}

const out = {
  source: "agent/agent.clean.js",
  builder: roles.envelope,
  params,
  keys: rows,
  spreads,
};

writeFileSync(join(REFERENCE, "envelope.json"), JSON.stringify(out, null, 2));

writeFileSync(
  join(REFERENCE, "envelope.md"),
  [
    "# Request envelope",
    "",
    `Generated by \`npm run envelope\` from \`agent/agent.clean.js\`, off \`${roles.envelope}\`.`,
    "One row per wire key that is not an `sN` signal. `signals.md` covers the rest.",
    "",
    "| key | built from |",
    "| --- | --- |",
    ...rows.map((row) => `| \`${row.key}\` | \`${row.expression}\` |`),
    "",
    "## Spread in",
    "",
    ...(spreads.length
      ? spreads.flatMap((spread) => [
          spread.passthrough
            ? `\`${spread.expression}\` writes through a computed key: one wire key per key of its` +
              " input, which is where the `sN` signal ids enter the envelope. It unwraps each" +
              " collector result to its `value`, or to the flattened `error`."
            : `\`${spread.expression}\` contributes ${spread.keys.length} keys:`,
          "",
          ...(spread.passthrough || !spread.keys.length
            ? []
            : [spread.keys.map((key) => `\`${key}\``).join(", "), ""]),
        ])
      : ["Nothing.", ""]),
    "## Builder arguments",
    "",
    "| argument | default |",
    "| --- | --- |",
    ...params.map(
      (param) => `| \`${param.name}\` | ${param.fallback ? `\`${param.fallback}\`` : "-"} |`,
    ),
    "",
  ].join("\n"),
);

console.log(`builder  ${roles.envelope}`);
console.log(`keys     ${rows.length}`);
console.log(`spreads  ${spreads.length}`);
console.log(`out      ${join(REFERENCE, "envelope.md")}`);
