#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parse } from "@babel/parser";
import { REFERENCE, CLEAN_AGENT } from "./lib/paths.mjs";
import { detectPrimitives } from "./lib/detect.mjs";
import { collectSignalRegistries } from "./lib/passes.mjs";
import { buildSurface, exclusiveOwners, rankByRarity } from "./lib/surface.mjs";

const SUMMARY_WIDTH = 6;
const source = readFileSync(CLEAN_AGENT, "utf8");
const ast = parse(source, {
  sourceType: "module",
});
const registries = collectSignalRegistries(ast);
const { roles } = detectPrimitives(ast);
const { index, collect } = buildSurface(ast, {
  hashName: roles.hash128,
});

const roots = registries.flatMap(({ entries }) => entries.map(({ binding }) => binding));

const ownership = exclusiveOwners(index, [...new Set(roots)]);

const ownedBy = (root) =>
  new Set([...ownership].filter(([, owner]) => owner === root).map(([name]) => name));

const modules = registries.map(({ key, entries }) => ({
  key,
  signals: entries.map(({ id, stage, binding }) => ({
    id,
    stage,
    binding,
    ...collect(binding, {
      owned: ownedBy(binding),
    }),
  })),
}));

const everySignal = modules.flatMap((module) => module.signals);
const rank = rankByRarity(everySignal.map((signal) => signal.apis));
const rankEngine = rankByRarity(everySignal.map((signal) => signal.engine));

for (const signal of everySignal) {
  signal.apis = rank(signal.apis);
  signal.engine = rankEngine(signal.engine);
  signal.summary = (signal.apis.length ? signal.apis : signal.engine)
    .slice(0, SUMMARY_WIDTH)
    .join(", ");
}

const out = {
  source: "agent/agent.clean.js",
  modules,
  totals: {
    modules: modules.length,
    signals: everySignal.length,
    withoutApis: everySignal.filter((signal) => signal.apis.length === 0).length,
    engineOnly: everySignal.filter((signal) => !signal.apis.length && signal.engine.length).length,
    withoutSurface: everySignal.filter((signal) => !signal.apis.length && !signal.engine.length)
      .length,
    branchless: everySignal.filter((signal) => !signal.checks.length && !signal.truncated).length,
    truncated: everySignal.filter((signal) => signal.truncated).length,
  },
};

writeFileSync(join(REFERENCE, "signals.json"), JSON.stringify(out, null, 2));

const rows = [];

for (const module of modules) {
  for (const signal of module.signals) {
    const probes = signal.probes
      .slice(0, 6)
      .map((value) => `\`${value}\``)
      .join(" ");
    const shape = signal.shapes.join(" ") || "-";
    rows.push(
      `| ${signal.id} | ${module.key} | ${signal.stage.replace("stage", "")} | ${signal.binding} | ${signal.codes.join(" ") || "-"} | \`${shape}\` | ${signal.hashed ? "yes" : "-"} | ${signal.summary || "-"} | ${probes || "-"} |`,
    );
  }
}

const numeric = (row) => Number(row.slice(3).split(" ")[0]);

rows.sort((a, b) => numeric(a) - numeric(b));

const byId = [...everySignal].sort((a, b) => Number(a.id.slice(1)) - Number(b.id.slice(1)));

const detail = byId
  .filter((signal) => signal.checks.length || signal.constants.length)
  .flatMap((signal) => [
    `### ${signal.id} — \`${signal.binding}\``,
    "",
    `[slice](slices/${signal.id}.js) · codes ${signal.codes.join(" ") || "none"} · v \`${signal.shapes.join(" ") || "-"}\`${signal.truncated ? " · walk truncated, checks incomplete" : ""}`,
    "",
    ...(signal.engine.length
      ? [
          `engine: ${signal.engine
            .slice(0, 6)
            .map((api) => `\`${api}\``)
            .join(" ")}`,
          "",
        ]
      : []),
    ...(signal.constants.length
      ? [`compares: ${signal.constants.map((value) => `\`${value}\``).join(" ")}`, ""]
      : []),
    ...(signal.checks.length
      ? [...signal.checks.map((check) => `- \`${check.replace(/`/g, "'")}\``), ""]
      : []),
  ]);

writeFileSync(
  join(REFERENCE, "signals.md"),
  [
    "# Signal map",
    "",
    "Generated by `npm run signals` from `agent/agent.clean.js`. One row per wire signal id.",
    "`codes` are the `s` values the collector and everything it reaches can return; `APIs` are the",
    "browser surfaces it touches, rarest-first; `probes` are the string literals in its own body and",
    "its direct helpers, which is where the names behind a computed lookup end up.",
    "",
    "Stage `request` means the id is contributed by the module's `toRequest`, not by a `sources`",
    "stage — those ids ride the wire like any other but are collected as the payload is assembled.",
    "",
    "`v` is the shape of the reported value where it is a literal in the source: object keys for an",
    "object, a kind otherwise, `call` where it comes back from a helper. `hashed` means the collector",
    "or one of its direct helpers reaches the x64-128 mixer, so what rides the wire is a digest and",
    "has to be reproduced rather than edited.",
    "",
    "A few collectors read no browser surface at all: what they measure is the engine, and their",
    "`APIs` column carries that instead — a `Math.random` sequence, the byte order of a NaN in a",
    "`Float32Array`, whether `Error.stack` is populated.",
    "",
    "| id | module | stage | binding | codes | v | hashed | APIs | probes |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
    "## What each collector decides on",
    "",
    "The tests a collector and its helpers branch on, and the constants those tests compare against.",
    "A helper named `h_<id>_*` is reachable from that collector alone; a bare `fnN` is shared with",
    "others. Per-signal source is in `slices/`.",
    "",
    ...detail,
  ].join("\n"),
);

console.log(`modules     ${out.totals.modules}`);
console.log(`signals     ${out.totals.signals}`);
console.log(`engine only ${out.totals.engineOnly}`);
console.log(`no surface  ${out.totals.withoutSurface}`);
console.log(`branchless  ${out.totals.branchless}`);
console.log(`truncated   ${out.totals.truncated}`);
console.log(`out      ${join(REFERENCE, "signals.json")}`);
console.log(`out      ${join(REFERENCE, "signals.md")}`);
